services:

  frontend:
    build:
      context: ./app/frontend
    security_opt:
      - no-new-privileges:true

    container_name: platform-frontend

    ports:
      - "5173:80"

    restart: unless-stopped


  backend:
    build:
      context: ./app/backend
    security_opt:
      - no-new-privileges:true

    container_name: platform-backend

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      FRONTEND_URL: ${FRONTEND_URL}
      ENVIRONMENT: ${ENVIRONMENT}
      APP_VERSION: ${APP_VERSION}

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped


  postgres:
    image: postgres:16-alpine

    container_name: platform-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U platform -d platform"
        ]

      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped


volumes:
  postgres_data:
