name: Build and Push to ECR

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: ci
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2
      
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 732108543574.dkr.ecr.eu-west-2.amazonaws.com
      
      - name: Build and push backend
        run: |
          docker build -t 732108543574.dkr.ecr.eu-west-2.amazonaws.com/gambit-backend:latest -f Dockerfile.backend .
          docker push 732108543574.dkr.ecr.eu-west-2.amazonaws.com/gambit-backend:latest
      
      - name: Build and push frontend
        run: |
          docker build -t 732108543574.dkr.ecr.eu-west-2.amazonaws.com/gambit-frontend:latest -f Dockerfile.frontend .
          docker push 732108543574.dkr.ecr.eu-west-2.amazonaws.com/gambit-frontend:latest